name: CD deploy main
on:
  push:
    branches:
      - verygood
jobs:
  deploy-main:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.TWENTY_INFRA_TOKEN }}
          repository: akfreas/verygood-infra
          event-type: auto-deploy-twenty
          client-payload: '{"github": ${{ toJson(github) }}}' # Passes the entire github context to the downstream workflow
